# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
 runner that the job will run on
    runs-on: ubuntu-latest
    - name: Send greeting
